### ISSUE TITLE
Bug with local

### ISSUE THREAD

**Issue by ajdelhaise** [stfrigerio/sqliteDB#4]
I had issues getting a line/bar charts to function in local mode, here are the issues I found:

1. Error: `TypeError: r.values.map is not a function` - `\src\codeblocks\processSqlChartBlock\index.ts`, Line 68 passes the wrong variable to processChartData(). `rows` should be `{ columns, values }`
2. Error: `window.renderChart is not a function` - Chart.js is not bundled or loaded, but the code expects window.renderChart to exist.

Otherwise excellent plugin, cheers :)

**Comment by stfrigerio** [comment]
Hello there! Thank you for reaching out, I'm glad that you are finding it useful :)

I've pushed a small update to fix the wrong variable, and bundled Chart.js into the code, I was in fact relying `obsidian-chart` (I believe?) to have Chart.js available. Not it should work on its own.

Lemme know if this fixes it for you, and if you need something else! always happy to add more stuff :)
